<?= $this->insert('overall/header') ?>
  <body class="login">
    <div>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form id="form_login">
              <div class="">
                <img src="views/logo_lg.png" class="img-responsive" alt="" />
              </div>
              <hr>
              <div>
                <input type="email" class="form-control" name="email" placeholder="Usuario" required="" />
              </div>
              <div>
                <input type="password" class="form-control" name="pass" placeholder="Contraseña" required="" />
              </div>
              <div>
                <button type="button" class="btn btn-primary" id="btn_login_send">Iniciar Sesion</button>
              </div>

              <div class="clearfix"></div>
              <div class="separator">
                <div class="clearfix"></div>
                <br />
                <div>
                  <p>© <?= date("Y") ?> Todos los Derechos Reservados. <?= APP ?></p>
                </div>
              </div>
              <div id="ajax_login">

                <div class="alert alert-info alert-dismissible fade in" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                  <strong>Correcto</strong>, te estamos redireccionando...
                </div>
              
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
    <?= $this->insert('overall/footer', array("mostrar" => false)) ?>

  </body>
</html>
