<?= $this->insert('overall/header') ?>
  <body class="hold-transition login-page" style="background-image:url('https://static.pexels.com/photos/38556/office-notes-notepad-entrepreneur-38556-large.jpeg');background-size:cover;">
    <div class="login-box">
      <!-- /.login-logo -->
      <div class="login-box-body">
        <div class="login-logo">
            <img src="views/logo_lg.png" class="img-responsive" alt="" />
        </div>
        <p class="login-box-msg">Inicio de Sesion para el Panel Administrativo</p>
        <form id ="login_form">
          <div class="form-group has-feedback">
            <input type="email" class="form-control" name="email" placeholder="Usuario">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" name="pass" placeholder="Contraseña">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <!-- /.col -->
            <div class="col-xs-12">
              <button id="login_form_btn" class="btn btn-primary btn-block btn-flat">Iniciar Sesion</button>
            </div>
            <!-- /.col -->
          </div>
        </form>
        <div id="ajax_login">

        </div>
      </div>
      <!-- /.login-box-body -->
    </div>
    <?= $this->insert('overall/js') ?>
    <script src="views/app/js/login.js" charset="utf-8"></script>
  </body>
</html>
