<?= $this->insert('overall/header') ?>
<body>
  <?= $this->insert('overall/topnav') ?>
  <div id="content">

    <div class="container">
        <div class="col-md-12">
          <!-- /#main-slider -->
            <div id="main-slider">

              <?php foreach ( $imagenes as $img ): ?>
                    <a href="#" class="item">
                        <img src="<?= $img ?>" alt="" class="img-responsive">
                    </a>
                <?php endforeach ?>
            </div>
            <!-- /#main-slider -->
        </div>

        <a href="home2">PERRITA GRAMPUTA</a>
    </div>
      <?= $this->insert('overall/footer') ?>
  </div>
</body>
</html>
