<!DOCTYPE html>
<html lang="es">

<head>
    <base href="<?= URL ?>" />
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Obaju e-commerce template">
    <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
    <meta name="keywords" content="">
    <meta name="application-name" content="<?= APP ?>" />
    <!--Titulo-->
    <title><?= APP ?></title>

    <!-- styles -->
    <link href="views/app/css/font-awesome.css" rel="stylesheet">
    <link href="views/app/css/bootstrap.min.css" rel="stylesheet">
    <link href="views/app/css/animate.min.css" rel="stylesheet">
    <link href="views/app/css/owl.carousel.css" rel="stylesheet">
    <link href="views/app/css/owl.theme.css" rel="stylesheet">

    <!-- theme stylesheet -->
    <link href="views/app/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

    <!-- your stylesheet with modifications -->
    <link href="views/app/css/custom.css" rel="stylesheet">

    <script src="views/app/js/respond.min.js"></script>

    <link rel="shortcut icon" href="views/app/favicon.ico">

</head>
