<!-- *** NAVBAR ***
_________________________________________________________ -->

<div class="navbar navbar-default yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand home" href="home/">
                <img src="views/app/images/logo.png" alt="Obaju logo" class="hidden-xs">
                <img src="views/app/images/logo-small.png" alt="Obaju logo" class="visible-xs"><span class="sr-only">MPLC-Inicio</span>
            </a>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">MENU</span>
                    <i class="fa fa-align-justify"></i>
                </button>

            </div>
        </div>
        <!--/.navbar-header -->

        <div class="navbar-collapse collapse" id="navigation">

            <ul class="nav navbar-nav navbar-left">
                <li class="active"><a href="home/">Inicio</a>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Municipalidad <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h5>Nosotros</h5>
                                        <ul>
                                            <li><a href="category.html">Mision y Vision</a>
                                            </li>
                                            <li><a href="category.html">Organigramas</a>
                                            </li>
                                            <li><a href="category.html">Autoridades</a>
                                            </li>
                                            <li><a href="category.html">Ley Organica de Municipalidades</a>
                                            </li>
                                            <li><a href="category.html">Directorio de Telefonico</a>
                                            </li>
                                            <li><a href="category.html">Reconocimientos</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Gerencias</h5>
                                        <ul>
                                            <li><a href="category.html">Gerencia de Administracion</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Desarrollo Agrario y Economico</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Desarrollo Social</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Desarrollo Urbano, Rural y Transportes</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Infraestructura Publica</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Recursos Naturales y Gestion Ambiental</a>
                                            </li>
                                            <li><a href="category.html">Gerencia de Rentas</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Programas Especiales</h5>
                                        <ul>
                                            <li><a href="category.html">Programa del Vaso de Leche</a>
                                            </li>
                                            <li><a href="category.html">Programa Especial Terminal Terrestre</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Comite</h5>
                                        <ul>
                                            <li><a href="category.html">Concejo de Coordinacion Local Provincial</a>
                                            </li>
                                            <li><a href="category.html">Comite Provincial de Defensa Civil</a>
                                            </li>
                                            <li><a href="category.html">Comite Provincial de Seguridad Ciudadana</a>
                                            </li>
                                            <li><a href="category.html">Comite Provincial de Medio Ambiente</a>
                                            </li>
                                            <li><a href="category.html">Comite Provincial de Administracion PVL</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>


                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Transparencia <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h5>Documentos de Gestion</h5>
                                        <ul>
                                            <li><a href="index.html">Acuerdos de Concejo</a>
                                            </li>
                                            <li><a href="category.html">Decretos de Alcaldia</a>
                                            </li>
                                            <li><a href="category-right.html">Ordenanzas Municipales</a>
                                            </li>
                                            <li><a href="category-full.html">Reglamentos</a>
                                            </li>
                                            <li><a href="detail.html">Resoluciones de Alcaldia</a>
                                            </li>
                                            <li><a href="category-full.html">Resoluciones de Gerencia Municipal</a>
                                            </li>
                                            <li><a href="category-full.html">Actas de Sesiones de Concejo</a>
                                            </li>
                                            <li><a href="category-full.html">Agenda de Sesiones de Concejo</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Documentos de Interes</h5>
                                        <ul>
                                            <li><a href="register.html">Presupuesto Inicial de Apertura 2016</a>
                                            </li>
                                            <li><a href="customer-orders.html">Plan Anual de Contrataciones 2016</a>
                                            </li>
                                            <li><a href="customer-order.html">Plan Estrategico Institucional</a>
                                            </li>
                                            <li><a href="customer-wishlist.html">Plan Operativo Institucional</a>
                                            </li>
                                            <li><a href="customer-account.html">Plan de Desarrollo Concentrado</a>
                                            </li>
                                            <li><a href="customer-account.html">Informacion Legal</a>
                                            </li>
                                            <li><a href="customer-account.html">Ley de Transparencia y Acceso Publico</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-4">
                                        <h5>Comision de Transparencia</h5>
                                        <ul>
                                            <li><a href="basket.html">Comision de Transparencia</a>
                                            </li>
                                            <li><a href="checkout1.html">Salario del Alcalde y Viaticos de Func.</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-2">
                                        <h5>Obras</h5>
                                        <ul>
                                            <li><a href="blog.html">Obras Ejecutadas</a>
                                            </li>
                                            <li><a href="post.html">Obras en Ejecucion</a>
                                            </li>
                                            <li><a href="faq.html">Proximas Obras</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Servicios <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <h5>Servicios</h5>
                                        <ul>
                                            <li><a href="index.html">Cultura y Educacion</a>
                                            </li>
                                            <li><a href="index.html">Salud</a>
                                            </li>
                                            <li><a href="index.html">Adulto Mayor</a>
                                            </li>
                                            <li><a href="index.html">Deportes</a>
                                            </li>
                                            <li><a href="index.html">Talleres</a>
                                            </li>
                                            <li><a href="index.html">Programas para Jovenes</a>
                                            </li>
                                            <li><a href="index.html">Bolsa de Trabajo</a>
                                            </li>
                                            <li><a href="index.html">Presupuesto Participativo</a>
                                            </li>
                                            <li><a href="index.html">Participacion Vecinal</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-4">
                                        <h5>Seguridad</h5>
                                        <ul>
                                          <li><a href="index.html">Serenazgo</a>
                                          </li>
                                          <li><a href="index.html">Policia Municipal</a>
                                          </li>
                                          <li><a href="index.html">Defensa Civil</a>
                                          </li>
                                          <li><a href="index.html">INDECI</a>
                                          </li>
                                          <li><a href="index.html">Video Vigilancia</a>
                                          </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-4">
                                        <h5>Tramites</h5>
                                        <ul>
                                          <li><a href="index.html">TUPA</a>
                                          </li>
                                          <li><a href="index.html">Matrimonio Civil</a>
                                          </li>
                                          <li><a href="index.html">Tributos Municipales</a>
                                          </li>
                                          <li><a href="index.html">Licencia de Construccion</a>
                                          </li>
                                          <li><a href="index.html">Licencia de Funcionamiento</a>
                                          </li>
                                          <li><a href="index.html">Impuestro Predial</a>
                                          </li>
                                          <li><a href="index.html">Campañas</a>
                                          </li>
                                        </ul>
                                    </div>

                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">La Convencion <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">

                                <div class="row">
                                    <div class="col-sm-12">
                                        <h5>La Convecion</h5>
                                        <ul>
                                            <li><a href="index.html">Historia de La Convencion</a>
                                            </li>
                                            <li><a href="index.html">Himno a La Convencion</a>
                                            </li>
                                            <li><a href="index.html">Atractivos Turisticos</a>
                                            </li>
                                            <li><a href="index.html">Geografia</a>
                                            </li>
                                            <li><a href="index.html">Documentos Historicos</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Publicaciones <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">

                                <div class="row">
                                    <div class="col-sm-12">
                                        <h5>Publicaciones</h5>
                                        <ul>
                                            <li><a href="index.html">Agenda del Alcalde</a>
                                            </li>
                                            <li><a href="index.html">Noticias</a>
                                            </li>
                                            <li><a href="index.html">Notas de Prensa</a>
                                            </li>
                                            <li><a href="index.html">Comunicados</a>
                                            </li>
                                            <li><a href="index.html">Eventos</a>
                                            </li>
                                            <li><a href="index.html">Convocatorias</a>
                                            </li>
                                            <li><a href="index.html">Licitaciones</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>
            </ul>

        </div>

    </div>
    <!-- /.container -->
</div>
<!-- /#navbar -->

<!-- *** NAVBAR END *** -->
