<?= $this->insert('overall/header') ?>
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <?= $this->insert('overall/topnav') ?>
        <!-- page content -->
        <div class="right_col" role="main">
          <div class="row">

            <h1>Pagina en Blanco</h1>
            <h2>Pagina en Blanco</h2>
            <h3>Pagina en Blanco</h3>
            <h4>Pagina en Blanco</h4>
          </div>
        </div>
        <!-- /page content -->

        <?= $this->insert('overall/footer') ?>
      </div>
    </div>

  </body>
</html>
