<script>
    var Dashboard = function() {

        return {

            initAmChart4: function() {
                if (typeof(AmCharts) === 'undefined' || $('#dashboard_amchart_4').size() === 0) {
                    return;
                }

                var chart = AmCharts.makeChart("dashboard_amchart_4", {
                    "type": "pie",
                    "theme": "light",
                    "path": "views/backend/global/plugins/amcharts/ammap/images/",
                    "dataProvider": <?= $divisas ?>,
                    "valueField": "cantidad",
                    "titleField": "divisa",
                    "outlineAlpha": 0.4,
                    "depth3D": 15,
                    "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
                    "angle": 30,
                    "export": {
                        "enabled": true
                    }
                });
                jQuery('.chart-input').off().on('input change', function() {
                    var property = jQuery(this).data('property');
                    var target = chart;
                    var value = Number(this.value);
                    chart.startDuration = 0;

                    if (property == 'innerRadius') {
                        value += "%";
                    }

                    target[property] = value;
                    chart.validateNow();
                });
            },

            init: function() {

                this.initAmChart4();

            }
        };

    }();

    if (App.isAngularJsApp() === false) {
        jQuery(document).ready(function() {
            Dashboard.init(); 
        });
    }
</script>