<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<?php if (true == DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
<script src="views/app/js/jquery.js"></script>
<?php endif ?>
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->


<?php if ($mostrar): ?>
  <!-- footer content -->
  <footer>
    <div class="pull-right">
      Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
  </footer>
  <!-- /footer content -->
<?php endif; ?>

<!-- jQuery -->
<script src="views/app/css/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="views/app/css/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="views/app/css/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="views/app/css/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="views/app/css/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="views/app/css/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="views/app/css/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="views/app/css/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="views/app/css/skycons/skycons.js"></script>
<!-- Flot -->
<script src="views/app/css/Flot/jquery.flot.js"></script>
<script src="views/app/css/Flot/jquery.flot.pie.js"></script>
<script src="views/app/css/Flot/jquery.flot.time.js"></script>
<script src="views/app/css/Flot/jquery.flot.stack.js"></script>
<script src="views/app/css/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="views/app/css/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="views/app/css/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="views/app/css/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="views/app/css/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="views/app/css/jqvmap/dist/jquery.vmap.js"></script>
<script src="views/app/css/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="views/app/css/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="views/app/js/moment/moment.min.js"></script>
<script src="views/app/js/datepicker/daterangepicker.js"></script>

<!-- Custom Theme Scripts -->
<script src="views/app/js/custom.min.js"></script>
