<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<?php if (true == DEBUG): ?>
<script src="views/app/js/jdev.js"></script>
<?php else: ?>
<script src="views/app/js/jquery.js"></script>
<?php endif ?>
<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
<!-- jQuery 2.2.3 -->
<script src="views/app/plugins/jQuery/jquery-2.2.3.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="views/app/bootstrap/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="views/app/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="views/app/plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="views/app/dist/js/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="views/app/dist/js/demo.js"></script>
